name: Nightly Garmin Sync
on:
  schedule:
    - cron: '0 6 * * *' # Runs at 6 AM UTC daily
  workflow_dispatch:
    inputs:
      activity_id:
        description: 'Optional: A specific Garmin activity ID to refresh (e.g., 12345678901)'
        required: false
        type: string

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
      GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
      GARMIN_2FA: ${{ secrets.GARMIN_2FA_SECRET }}
      VISUAL_CROSSING_API_KEY: ${{ secrets.VISUAL_CROSSING_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Garmin Scraper
        run: python3 scripts/garmin_scraper.py ${{ github.event.inputs.activity_id || '' }}

      - name: Run Garmin to Daily Files Converter
        run: python3 scripts/garmin_to_daily_files.py

      - name: Add Structured Human-Readable Formatting
        run: python3 scripts/add_structured_human_readable.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "auto: $(date +'%Y-%m-%d') Garmin data sync"
          add: "data/"
          default_author: github_actions 